var questionQueenLingo = [
	"What does fishy mean?",
	"What does spilling the tea mean?",
	"What does snatched mean?",
	"What does beat mean?",
	"What does ki ki mean?",
	"What does tucking mean?",
	"What does kai kai mean?",
	"What does trade mean?",
	"What does shade mean?",
	"What do cakes refer to?",
	"What does serving cheescake mean?",
	"Jesus is a biscuit so....",
	"What does clocking someone mean?",
	"What is a faux queen?",
	"What does feeling my oats mean?",
	"What are the 5 G's"
	"What does for the gods mean?",
	"What does for days mean?",
	"What does hunty stand for?",
	"What is a death drop?",
	"What does trade mean?",
	"What does mug mean?",
	"What does reading mean?",
	"What does sick'ning mean?",
	"What does sissy that walk mean?",
	"What does squirrel friends mean?",
];

var answersQueenLingo = [
	["You look like a real girl", "You smell bad", "You are acting sketchy", "You like to drink too much"],
	["You are clumsy", "Give me the gossip", "Who even drinks tea?" , ""],
	["Stealing something", "Looking perfect", "Looking like you have a vagina", "Stealing a wig"],
	["Looking ugly","Dancing with the rythm","Having flawless face makeup", "To win a contest"],
	["A gossip sesion", "Kinky", "Sex", "A girly name"],
	["Plastic surgery", "Fixing your clothes", "Hiding you dick", "Doing a perfect flip"],
	["A quickie", "Drag Queen Sex", "Nickname for Kylie", ""],
	["Mumbai","Hyderabad","Bangalore","New Delhi"]];

var correctAnswersQueenLingo = [
	"A. You look like a real girl",
	"B. Give me the gossip",
	"C. Taipei",
	"C. Tokyo",
	"D. Beijing",
	"A. Ankara",
	"B. Bogota",
	"D. New Delhi"
];

var questionsQueenPicture = [
	"Willaim Belli",
	"RuPaul",
	"Ornacia",
	"Alaska",
	"Courtney Act",
	"Alyssa Edwards",
	"Bianca del Rio",
	"Latrice Royale",
	"Katya",
	"Sharon Needles",
	"Bob the Drag Queen",
	"Jinx Monsoon",
	"Detox",
	"Raven"
	"Raja",
	"Jujubee",
	"Chad Michaels",
	"Manila Luzon",
	"Kim Chi",
	"Roxxxy Andrews",
	"Valentina",
	"Tatiana",
	"Shangela",
	"Adore Delano",
	"Pandora Boxx",
	"Violet Chachki",
	"Trixie Mattel",
	"BenDeLaCreme",
	"Laganja Estranja",
	"Darienne Lake",
	"Coco Montrese",
	"Milk",
	"Trinity K. Bonet",
	"Ongina",
	"Miss Fame",
	"Carmen Carrera",
	"Delta Work",
	"Jiggly Caliente",
	"Tammie Brown",
	"Ivy Winters",
	"Yara Sofia",
	"Stacy Layne Matthews",
	"Gia Gunn",
	"Vivacious",
	"Kenya Michaels",
	"Phi Phi O'Hara",
	"Jessica Wild",
	"Madame LaQueer",
	"April Carrion",
	"Magnolia Crawford",
	"Mariah",
	"Nicole Paige Brooks",
	"Mystique",
	"Joslyn Fox",
];

var answersQueenPicture = [
	"Willaim Belli",
	"RuPaul",
	"Ornacia",
	"Alaska",
	"Courtney Act",
	"Alyssa Edwards",
	"Bianca del Rio",
	"Latrice Royale",
	"Katya",
	"Sharon Needles",
	"Bob the Drag Queen",
	"Nina Flowers",
	"Jinx Monsoon",
	"Detox",
	"BeBe Zahara Benet",
	"Raven"
	"Raja",
	"Jujubee",
	"Chad Michaels",
	"Manila Luzon",
	"Kim Chi",
	"Roxxxy Andrews",
	"Valentina",
	"Tatiana",
	"Shangela",
	"Adore Delano",
	"Pandora Boxx",
	"Violet Chachki",
	"Trixie Mattel",
	"BenDeLaCreme",
	"Laganja Estranja",
	"Pearl",
	"Darienne Lake",
	"Coco Montrese",
	"Milk",
	"Trinity K. Bonet",
	"Ongina",
	"Miss Fame",
	"Carmen Carrera",
	"Delta Work",
	"Jiggly Caliente",
	"Tammie Brown",
	"Ivy Winters",
	"Sahara Davenport",
	"Yara Sofia",
	"Mimi Imfurst",
	"Milan",
	"Dida Ritz",
	"Stacy Layne Matthews",
	"Alexis Mateo",
	"Gia Gunn",
	"Jade Jolie",
	"Lashauwn Beyond",
	"Vivacious",
	"Porkchop",
	"Kenya Michaels",
	"Vivienne Pinay",
	"The Princess",
	"Honey Magohany",
	"Shannel",
	"Monica Beverly Hillz",
	"Rebecca Glasscock",
	"Phi Phi O'Hara",
	"India Ferrah",
	"Jessica Wild",
	"Madame LaQueer",
	"April Carrion",
	"Magnolia Crawford",
	"Serena ChaCha",
	"Mariah",
	"Nicole Paige Brooks",
	"Sonique",
	"Alisa Summers",
	"Jade",
	"Penny Tration",
	"Venus D-Lite",
	"Mystique",
	"Joslyn Fox",
];


/*var imageArray = ["<img class='center-block img-right' src='img/australia.png'>", "<img class='center-block img-right' src='img/liberia.png'>", "<img class='center-block img-right' src='img/taiwan.png'>", "<img class='center-block img-right' src='img/japan.png'>", "<img class='center-block img-right' src='img/china.png'>", "<img class='center-block img-right' src='img/turkey.png'>", "<img class='center-block img-right' src='img/colombia.png'>", "<img class='center-block img-right' src='img/india.png'>"];*/