
//Quiz Data for Queen Lingo
var questionQueenLingo = [
	"What does fishy mean?",
	"What does spilling the tea mean?",
	"What does snatched mean?",
	"What does beat mean?",
	"What does ki ki mean?",
	"What does tucking mean?",
	"What does kai kai mean?",
	"What do cakes refer to?",
	"Jesus is a biscuit....",
	"What does serving cheescake mean?",
	"What does trade mean?",
	"What does shade mean?",
	"What does clocking someone mean?",
	"What is a faux queen?",
	"What does feeling my oats mean?",
	"What are the 5 G's",
	"What does for the gods mean?",
	"What does for days mean?",
	"What does hunty stand for?",
	"What is a death drop?",
	"What does mug mean?",
	"What does reading mean?",
	"What does sick'ning mean?",
	"What does squirrel friends mean?"
];

var answersQueenLingo = [
	["You look like a real girl", "You smell bad", "You are acting sketchy", "You like to drink too much"],
	["You are clumsy", "Give me the gossip", "Who even drinks tea?", "Saying somehting stupid"],
	["Stealing something", "Looking perfect", "Looking like you have a vagina", "Stealing a wig"],
	["Looking ugly", "Dancing with the rythm", "Having flawless face makeup", "To win a contest"],
	["A gossip session", "Kinky", "Sex", "A girly name"],
	["Plastic surgery", "Fixing your clothes", "Hiding your dick", "Doing a perfect flip"],
	["A quickie", "Drag Queen Sex", "Nickname for Kylie", "How Drag Queens say Okay"],
	["Face", "Thighs", "Ankles", "Ass"],
	["Jesus isn't a biscuit!", "Amen!", "So let him sop you up!", "With extra gravy!"],
	["A sexy thick girl", "Thick thighs", "Jiggly ass", "Looking rich"],
	["Swapping looks", "Changing wigs", "A 'straight' man who might go gay", "Making money"],
	["Another word for a shadow", "Pointing out someone's flaws", "Doing something sketchy", "A hue of a color"],
	["Stealing their time", "Hitting them in the face", "Ignoring them", "Noticing a flaw"],
	["A biologically female queen", "A lying queen", "A queen who only wants money", "A fake queen"],
	["Grabbing your ass", "To smoke weed", "Grab your balls", "To feel one's self"],
	["Go Get a Gurdle Girl, God!", "Good God, Get a Grip Girl!", "Gay Guys Get Great Girls!", "God Give me Good Gay Guys!"],
	["Done perfectly", "Hail Oden!", "The Old and the New", "OMG"],
	["Being talkative", "To have a lot of something", "Be experienced", "Doing drag during the day"],
	["Honey + tea", "Honey + aunty", "It doesn't stand for anything", "Honey + Cunt"],
	["To do a split", "To jump off stage", "Drop your wig on the floor", "To fall backwards into a struck pose"],
	["A face", "Stealing something", "A place to put coffee", "Bad makeup"],
	["To stare someone down", "To wittily expose a person's flaws", "Lipsyncing", "To be focused"],
	["To look gross", "To look skinny", "To be beyond awesome", "To look scary"],
	["Friends who hide their 'nuts'", "Best friends", "Friends who are crazy", "Friends who are sneaky"]
];

var correctAnswersQueenLingo = [
	"A. You look like a real girl",
	"B. Give me the gossip",
	"B. Looking perfect",
	"C. Having flawless face makeup",
	"A. A gossip session",
	"C. Hiding your dick",
	"B. Drag Queen Sex",
	"D. Ass",
	"C. So let him sop you up!",
	"A sexy thick girl",
	"A 'straight' man who might go gay",
	"Pointing out someone's flaws",
	"Noticing a flaw",
	"A biologically female queen",
	"To feel one's self",
	"Good God, Get a Grip Girl!",
	"Done perfectly",
	"To have a lot of something",
	"Honey + Cunt",
	"To fall backwards into a struck pose",
	"A face",
	"To wittily expose a person's flaws",
	"To be beyond awesome",
	"Friends who hide their 'nuts'"
];

//Quiz Data for Queen Facts
var questionQueenFacts = [
	"What does fishy mean?",
	"What does spilling the tea mean?",
	"What does snatched mean?",
	"What does beat mean?",
	"What does ki ki mean?",
	"What does tucking mean?",
	"What does kai kai mean?",
	"What do cakes refer to?",
	"Jesus is a biscuit....",
	"What does serving cheescake mean?",
	"What does trade mean?",
	"What does shade mean?",
	"What does clocking someone mean?",
	"What is a faux queen?",
	"What does feeling my oats mean?",
	"What are the 5 G's",
	"What does for the gods mean?",
	"What does for days mean?",
	"What does hunty stand for?",
	"What is a death drop?",
	"What does mug mean?",
	"What does reading mean?",
	"What does sick'ning mean?",
	"What does squirrel friends mean?"
];

var answersQueenFacts = [
	["You look like a real girl", "You smell bad", "You are acting sketchy", "You like to drink too much"],
	["You are clumsy", "Give me the gossip", "Who even drinks tea?", "Saying somehting stupid"],
	["Stealing something", "Looking perfect", "Looking like you have a vagina", "Stealing a wig"],
	["Looking ugly", "Dancing with the rythm", "Having flawless face makeup", "To win a contest"],
	["A gossip session", "Kinky", "Sex", "A girly name"],
	["Plastic surgery", "Fixing your clothes", "Hiding your dick", "Doing a perfect flip"],
	["A quickie", "Drag Queen Sex", "Nickname for Kylie", "How Drag Queens say Okay"],
	["Face", "Thighs", "Ankles", "Ass"],
	["Jesus isn't a biscuit!", "Amen!", "So let him sop you up!", "With extra gravy!"],
	["A sexy thick girl", "Thick thighs", "Jiggly ass", "Looking rich"],
	["Swapping looks", "Changing wigs", "A 'straight' man who might go gay", "Making money"],
	["Another word for a shadow", "Pointing out someone's flaws", "Doing something sketchy", "A hue of a color"],
	["Stealing their time", "Hitting them in the face", "Ignoring them", "Noticing a flaw"],
	["A biologically female queen", "A lying queen", "A queen who only wants money", "A fake queen"],
	["Grabbing your ass", "To smoke weed", "Grab your balls", "To feel one's self"],
	["Go Get a Gurdle Girl, God!", "Good God, Get a Grip Girl!", "Gay Guys Get Great Girls!", "God Give me Good Gay Guys!"],
	["Done perfectly", "Hail Oden!", "The Old and the New", "OMG"],
	["Being talkative", "To have a lot of something", "Be experienced", "Doing drag during the day"],
	["Honey + tea", "Honey + aunty", "It doesn't stand for anything", "Honey + Cunt"],
	["To do a split", "To jump off stage", "Drop your wig on the floor", "To fall backwards into a struck pose"],
	["A face", "Stealing something", "A place to put coffee", "Bad makeup"],
	["To stare someone down", "To wittily expose a person's flaws", "Lipsyncing", "To be focused"],
	["To look gross", "To look skinny", "To be beyond awesome", "To look scary"],
	["Friends who hide their 'nuts'", "Best friends", "Friends who are crazy", "Friends who are sneaky"]
];

var correctAnswersQueenFacts = [
	"You look like a real girl",
	"Give me the gossip",
	"Looking perfect",
	"Having flawless face makeup",
	"A gossip session",
	"Hiding your dick",
	"Drag Queen Sex",
	"Ass",
	"So let him sop you up!",
	"A sexy thick girl",
	"A 'straight' man who might go gay",
	"Pointing out someone's flaws",
	"Noticing a flaw",
	"A biologically female queen",
	"To feel one's self",
	"Good God, Get a Grip Girl!",
	"Done perfectly",
	"To have a lot of something",
	"Honey + Cunt",
	"To fall backwards into a struck pose",
	"A face",
	"To wittily expose a person's flaws",
	"To be beyond awesome",
	"Friends who hide their 'nuts'"
];


//Quiz Data for Queen Picture
var questionsQueenPicture = [
	"Willaim Belli",
	"RuPaul",
	"Phi Phi O'Hara",
	"Jessica Wild",
	"Madame LaQueer",
	"April Carrion",
	"Magnolia Crawford",
	"Mariah",
	"Nicole Paige Brooks",
	"Mystique",
	"Joslyn Fox",
	"Ornacia",
	"Alaska",
	"Courtney Act",
	"Sharon Needles",
	"Bob the Drag Queen",
	"Jinx Monsoon",
	"Detox",
	"Raven",
	"Raja",
	"Jujubee",
	"Chad Michaels",
	"Manila Luzon",
	"Kim Chi",
	"Roxxxy Andrews",
	"Valentina",
	"Tatiana",
	"Shangela",
	"Adore Delano",
	"Pandora Boxx",
	"Violet Chachki",
	"Trixie Mattel",
	"BenDeLaCreme",
	"Alyssa Edwards",
	"Bianca del Rio",
	"Latrice Royale",
	"Katya",
	"Laganja Estranja",
	"Darienne Lake",
	"Coco Montrese",
	"Milk",
	"Trinity K. Bonet",
	"Ongina",
	"Miss Fame",
	"Carmen Carrera",
	"Delta Work",
	"Jiggly Caliente",
	"Tammie Brown",
	"Yara Sofia",
	"Stacy Layne Matthews",
	"Gia Gunn",
	"Vivacious",
	"Kenya Michaels"
];

var answersQueenPicture = [
	"Willaim Belli",
	"RuPaul",
	"Ornacia",
	"Alaska",
	"Courtney Act",
	"Alyssa Edwards",
	"Bianca del Rio",
	"Latrice Royale",
	"Katya",
	"Sharon Needles",
	"Bob the Drag Queen",
	"Nina Flowers",
	"Jinx Monsoon",
	"Detox",
	"BeBe Zahara Benet",
	"Raven",
	"Raja",
	"Jujubee",
	"Chad Michaels",
	"Manila Luzon",
	"Kim Chi",
	"Roxxxy Andrews",
	"Valentina",
	"Tatiana",
	"Shangela",
	"Adore Delano",
	"Pandora Boxx",
	"Violet Chachki",
	"Trixie Mattel",
	"BenDeLaCreme",
	"Laganja Estranja",
	"Pearl",
	"Darienne Lake",
	"Coco Montrese",
	"Milk",
	"Trinity K. Bonet",
	"Ongina",
	"Miss Fame",
	"Carmen Carrera",
	"Delta Work",
	"Jiggly Caliente",
	"Tammie Brown",
	"Ivy Winters",
	"Sahara Davenport",
	"Yara Sofia",
	"Mimi Imfurst",
	"Milan",
	"Dida Ritz",
	"Stacy Layne Matthews",
	"Alexis Mateo",
	"Gia Gunn",
	"Jade Jolie",
	"Lashauwn Beyond",
	"Vivacious",
	"Porkchop",
	"Kenya Michaels",
	"Vivienne Pinay",
	"The Princess",
	"Honey Magohany",
	"Shannel",
	"Monica Beverly Hillz",
	"Rebecca Glasscock",
	"Phi Phi O'Hara",
	"India Ferrah",
	"Jessica Wild",
	"Madame LaQueer",
	"April Carrion",
	"Magnolia Crawford",
	"Serena ChaCha",
	"Mariah",
	"Nicole Paige Brooks",
	"Sonique",
	"Alisa Summers",
	"Jade",
	"Penny Tration",
	"Venus D-Lite",
	"Mystique",
	"Joslyn Fox"
];


